export { default as ServicesIntroImg } from './services-intro-img.jpg'
export { default as ServicesBannerImg } from './services-banner.png'

export { default as ServicesImg1 } from './services-image-1.jpg'
export { default as ServicesImg2 } from './services-image-2.webp'
export { default as ServicesImg3 } from './services-image-3.jpg'
export { default as ServicesImg4 } from './services-image-4.jpg'
export { default as ServicesImg5 } from './services-image-5.jpg'
export { default as ServicesImg6 } from './services-image-6.jpeg'
export { default as ServicesImg7 } from './services-image-7.jpg'
export { default as ServicesImg8 } from './services-image-8.jpg'
export { default as ServicesImg9 } from './services-image-9.jpg'
export { default as ServicesImg10 } from './services-image-10.jpg'

export { default as ServicesIcon1 } from './services-icon-1.png'
export { default as ServicesIcon2 } from './services-icon-2.png'
export { default as ServicesIcon3 } from './services-icon-3.png'
export { default as ServicesIcon4 } from './services-icon-4.png'
export { default as ServicesIcon5 } from './services-icon-5.png'
export { default as ServicesIcon6 } from './services-icon-6.png'
export { default as ServicesIcon7 } from './services-icon-7.png'
export { default as ServicesIcon8 } from './services-icon-8.png'
export { default as ServicesIcon9 } from './services-icon-9.png'
export { default as ServicesIcon10 } from './services-icon-10.png'