export const ICONS = {
	LOGO_LIGHT: 'logo-light',
	LOGO_DARK: 'logo-dark',
	ARROW_DOWN: 'arrow-down',
	USER: 'user',
	USER_ALT: 'user-alt',
	DOG: 'dog',
	PET_CARD: 'pet-card',
	MEDICAL_RECEIPT: 'medical-receipt',
	EXIT: 'exit',
	SHOW_PASSWORD: 'show-password',
	HIDE_PASSWORD: 'hide-password',
	CLOCK: 'clock',
	HEART_PULSE: 'heart-pulse',
	MICROSCOPE: 'microscope',
	SYRINGE: 'syringe',
	PET_BAG: 'pet-bag',
	TOOTH: 'tooth',
	LOCATION: 'location',
	PHONE: 'phone',
	MAIL_CHECKED: 'mail-checked',
	TRASH: 'trash',
	EDIT: 'edit',
} as const

export type IconsType = ValueOf<typeof ICONS>