export { appointmentsRouter } from './appointments'
export { authRouter } from './auth'
export { breedsRouter } from './breeds'
export { petsRouter } from './pets'
export { servicesRouter } from './services'
export { speciesRouter } from './species'
export { userRouter } from './user'
