name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ vh450.timeweb.ru }}
          username: ${{ cw31740 }}
          password: ${{ Brixecs0_0Dosya }}
          server-dir:  //здесь нужно указать папку вашего проекта на хостинге
